const ACTIONS={
    DATA_VERIFY_REQUEST :"DATA_VERIFY_REQUEST",
    DATA_VERIFY_SUCCESS :"DATA_VERIFY_SUCCESS",
    DATA_VERIFY_FAILURE:"DATA_VERIFY_FAILURE",

    // DATA_VERIFY_FEES_REQUEST :"DATA_VERIFY_FEES_REQUEST",
    // DATA_VERIFY_FEES_SUCCESS :"DATA_VERIFY_FEES_SUCCESS",
    // DATA_VERIFY_FEES_FAILURE:"DATA_VERIFY_FEES_FAILURE",

    // DATA_VERIFY_REQUEST :"DATA_VERIFY_REQUEST",
    // DATA_VERIFY_SUCCESS :"DATA_VERIFY_SUCCESS",
    // DATA_VERIFY_FAILURE:"DATA_VERIFY_FAILURE",
    
}
export default ACTIONS